// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF_tqNkwq5QAJ9hyU16rZ6reCLvx_kxA8',
    appId: '1:608231222196:web:8a8abe5f3b219a470ba0e1',
    messagingSenderId: '608231222196',
    projectId: 'campusnest-fd6e3',
    authDomain: 'campusnest-fd6e3.firebaseapp.com',
    storageBucket: 'campusnest-fd6e3.firebasestorage.app',
    measurementId: 'G-CMEP4ZYC0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdNwwMWqtHbBImF8smJmxialpARBicReE',
    appId: '1:608231222196:android:5c216d6f79757bc30ba0e1',
    messagingSenderId: '608231222196',
    projectId: 'campusnest-fd6e3',
    storageBucket: 'campusnest-fd6e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx8y_pGJmaTAaKKKYXNJvhmAmxc0mQXgY',
    appId: '1:608231222196:ios:9fd0d667d5e302c60ba0e1',
    messagingSenderId: '608231222196',
    projectId: 'campusnest-fd6e3',
    storageBucket: 'campusnest-fd6e3.firebasestorage.app',
    iosBundleId: 'com.example.buddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx8y_pGJmaTAaKKKYXNJvhmAmxc0mQXgY',
    appId: '1:608231222196:ios:9fd0d667d5e302c60ba0e1',
    messagingSenderId: '608231222196',
    projectId: 'campusnest-fd6e3',
    storageBucket: 'campusnest-fd6e3.firebasestorage.app',
    iosBundleId: 'com.example.buddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF_tqNkwq5QAJ9hyU16rZ6reCLvx_kxA8',
    appId: '1:608231222196:web:3febda4d6f04183e0ba0e1',
    messagingSenderId: '608231222196',
    projectId: 'campusnest-fd6e3',
    authDomain: 'campusnest-fd6e3.firebaseapp.com',
    storageBucket: 'campusnest-fd6e3.firebasestorage.app',
    measurementId: 'G-YCTWSKZZB2',
  );
}
